In [1]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
import mxnet as mx
from mxnet import nd
from mxnet.gluon import nn

[mx.cpu(), mx.gpu(), mx.gpu(1)]

D:\Programdata\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
D:\Programdata\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py:46: DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL


[cpu(0), gpu(0), gpu(1)]

In [3]:
x = nd.array([1,2,3])
x


[1. 2. 3.]
<NDArray 3 @cpu(0)>

In [4]:
x.context


cpu(0)

In [5]:
a = nd.array([1, 2, 3], ctx=mx.gpu())

In [6]:
a



[1. 2. 3.]
<NDArray 3 @gpu(0)>

In [8]:
#b = nd.random.uniform(shape=(2, 3), ctx=mx.gpu(1)) 

In [9]:
y = x.copyto(mx.gpu())
y


[1. 2. 3.]
<NDArray 3 @gpu(0)>

In [10]:
z = x.as_in_context(mx.gpu())
z


[1. 2. 3.]
<NDArray 3 @gpu(0)>

In [11]:
y.as_in_context(mx.gpu()) is y

True

In [12]:
y.copyto(mx.gpu()) is y

False

In [13]:
(z + 2).exp() * y


[ 20.085537 109.1963   445.2395  ]
<NDArray 3 @gpu(0)>

In [14]:
net = nn.Sequential()
net.add(nn.Dense(1))
net.initialize(ctx=mx.gpu())

In [15]:
net(y)


[[0.0068339 ]
 [0.01366779]
 [0.02050169]]
<NDArray 3x1 @gpu(0)>

In [16]:
net[0].weight.data()


[[0.0068339]]
<NDArray 1x1 @gpu(0)>